[package]
name = "png-msg"
version = "0.1.0"
edition = "2021"
authors = ["Kevin Jerome"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "=1.8.1"
clap = { version = "=3.1.17", features = ["derive"] }
